# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 31ffcb2656f22538fc8439e2ebf9f0ec5340403ca0cc46e363dc2ee572e2cb922a631a2948023b1868d2bc73d119e51524df5482b17ecb4d2832406b844dc0bd

test:
  secret_key_base: 699b46ad9a046c455e2e7e33afdd44ec0b64a821df32f13c8f218f9d5cea79603693994f7bc915ed4117817c0a9e115e0b2116a481b1b3419e2c941b1d84ec3e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
