require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BlockedPhoneNumbersController do

  # This should return the minimal set of attributes required to create a valid
  # BlockedPhoneNumber. As you add validations to BlockedPhoneNumber, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "phone_number" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BlockedPhoneNumbersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all blocked_phone_numbers as @blocked_phone_numbers" do
      blocked_phone_number = BlockedPhoneNumber.create! valid_attributes
      get :index, {}, valid_session
      assigns(:blocked_phone_numbers).should eq([blocked_phone_number])
    end
  end

  describe "GET show" do
    it "assigns the requested blocked_phone_number as @blocked_phone_number" do
      blocked_phone_number = BlockedPhoneNumber.create! valid_attributes
      get :show, {:id => blocked_phone_number.to_param}, valid_session
      assigns(:blocked_phone_number).should eq(blocked_phone_number)
    end
  end

  describe "GET new" do
    it "assigns a new blocked_phone_number as @blocked_phone_number" do
      get :new, {}, valid_session
      assigns(:blocked_phone_number).should be_a_new(BlockedPhoneNumber)
    end
  end

  describe "GET edit" do
    it "assigns the requested blocked_phone_number as @blocked_phone_number" do
      blocked_phone_number = BlockedPhoneNumber.create! valid_attributes
      get :edit, {:id => blocked_phone_number.to_param}, valid_session
      assigns(:blocked_phone_number).should eq(blocked_phone_number)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new BlockedPhoneNumber" do
        expect {
          post :create, {:blocked_phone_number => valid_attributes}, valid_session
        }.to change(BlockedPhoneNumber, :count).by(1)
      end

      it "assigns a newly created blocked_phone_number as @blocked_phone_number" do
        post :create, {:blocked_phone_number => valid_attributes}, valid_session
        assigns(:blocked_phone_number).should be_a(BlockedPhoneNumber)
        assigns(:blocked_phone_number).should be_persisted
      end

      it "redirects to the created blocked_phone_number" do
        post :create, {:blocked_phone_number => valid_attributes}, valid_session
        response.should redirect_to(BlockedPhoneNumber.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved blocked_phone_number as @blocked_phone_number" do
        # Trigger the behavior that occurs when invalid params are submitted
        BlockedPhoneNumber.any_instance.stub(:save).and_return(false)
        post :create, {:blocked_phone_number => { "phone_number" => "invalid value" }}, valid_session
        assigns(:blocked_phone_number).should be_a_new(BlockedPhoneNumber)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        BlockedPhoneNumber.any_instance.stub(:save).and_return(false)
        post :create, {:blocked_phone_number => { "phone_number" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested blocked_phone_number" do
        blocked_phone_number = BlockedPhoneNumber.create! valid_attributes
        # Assuming there are no other blocked_phone_numbers in the database, this
        # specifies that the BlockedPhoneNumber created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        BlockedPhoneNumber.any_instance.should_receive(:update).with({ "phone_number" => "MyString" })
        put :update, {:id => blocked_phone_number.to_param, :blocked_phone_number => { "phone_number" => "MyString" }}, valid_session
      end

      it "assigns the requested blocked_phone_number as @blocked_phone_number" do
        blocked_phone_number = BlockedPhoneNumber.create! valid_attributes
        put :update, {:id => blocked_phone_number.to_param, :blocked_phone_number => valid_attributes}, valid_session
        assigns(:blocked_phone_number).should eq(blocked_phone_number)
      end

      it "redirects to the blocked_phone_number" do
        blocked_phone_number = BlockedPhoneNumber.create! valid_attributes
        put :update, {:id => blocked_phone_number.to_param, :blocked_phone_number => valid_attributes}, valid_session
        response.should redirect_to(blocked_phone_number)
      end
    end

    describe "with invalid params" do
      it "assigns the blocked_phone_number as @blocked_phone_number" do
        blocked_phone_number = BlockedPhoneNumber.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BlockedPhoneNumber.any_instance.stub(:save).and_return(false)
        put :update, {:id => blocked_phone_number.to_param, :blocked_phone_number => { "phone_number" => "invalid value" }}, valid_session
        assigns(:blocked_phone_number).should eq(blocked_phone_number)
      end

      it "re-renders the 'edit' template" do
        blocked_phone_number = BlockedPhoneNumber.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BlockedPhoneNumber.any_instance.stub(:save).and_return(false)
        put :update, {:id => blocked_phone_number.to_param, :blocked_phone_number => { "phone_number" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested blocked_phone_number" do
      blocked_phone_number = BlockedPhoneNumber.create! valid_attributes
      expect {
        delete :destroy, {:id => blocked_phone_number.to_param}, valid_session
      }.to change(BlockedPhoneNumber, :count).by(-1)
    end

    it "redirects to the blocked_phone_numbers list" do
      blocked_phone_number = BlockedPhoneNumber.create! valid_attributes
      delete :destroy, {:id => blocked_phone_number.to_param}, valid_session
      response.should redirect_to(blocked_phone_numbers_url)
    end
  end

end
